# Generated by Django 2.2 on 2019-04-14 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('abbrev', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='unit',
            name='id',
        ),
        migrations.AlterField(
            model_name='unit',
            name='abbrev',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
    ]
