# Generated by Django 2.2 on 2019-04-18 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_app', '0005_auto_20190416_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='max_show_size',
            field=models.DecimalField(decimal_places=1, max_digits=12, null=True),
        ),
    ]
