# Generated by Django 2.2 on 2019-04-18 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_app', '0006_order_max_show_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=4, max_digits=12)),
                ('overdraft_limit', models.DecimalField(decimal_places=4, max_digits=12)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exchange_app.Account')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exchange_app.Currency')),
            ],
            options={
                'unique_together': {('account', 'currency')},
            },
        ),
    ]
