# Generated by Django 2.2 on 2019-04-18 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_app', '0007_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traderpermission',
            name='org',
        ),
        migrations.AddField(
            model_name='traderpermission',
            name='account',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='exchange_app.Account'),
            preserve_default=False,
        ),
    ]
