# Generated by Django 2.2 on 2019-04-21 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_app', '0008_auto_20190418_0236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='seller',
        ),
        migrations.AddField(
            model_name='trade',
            name='buy_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='buy_order_fills', to='exchange_app.Order'),
        ),
        migrations.AddField(
            model_name='trade',
            name='sell_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sell_order_fills', to='exchange_app.Order'),
        ),
    ]
