# Generated by Django 2.2 on 2019-04-21 22:03

from django.db import migrations, models
import exchange.util


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_app', '0009_auto_20190421_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expiration',
            field=models.DateTimeField(default=exchange.util.day_from_now),
        ),
    ]
