# Generated by Django 2.2 on 2019-04-22 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('exchange_app', '0010_auto_20190421_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='allowed_bidders',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instruments_on_which_we_can_bid', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='allowed_offerers',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instruments_on_which_we_can_offer', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='order',
            name='curr_slice',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='filled_quantity',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
    ]
