# Generated by Django 2.2 on 2019-04-24 00:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_app', '0012_auto_20190422_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='priority_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='allowed_bidders',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instruments_on_which_we_can_bid', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='allowed_offerers',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instruments_on_which_we_can_offer', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='max_show_size',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True),
        ),
    ]
