# Generated by Django 2.2 on 2019-04-27 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_app', '0014_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
