# Generated by Django 2.2 on 2019-04-27 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_app', '0016_login_socialaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialaccount',
            name='user',
        ),
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.DeleteModel(
            name='SocialAccount',
        ),
    ]
