# Generated by Django 2.2 on 2019-04-27 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exchange_app', '0017_auto_20190427_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('sub', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=255)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('social_account', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='exchange_app.SocialAccount')),
            ],
            options={
                'unique_together': {('social_account', 'timestamp')},
            },
        ),
    ]
