# Generated by Django 2.2 on 2019-05-10 04:02

from django.db import migrations, models
import exchange.util


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_app', '0019_trader_credit_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expiration',
            field=models.DateTimeField(default=exchange.util.long_time_in_future),
        ),
    ]
