# Generated by Django 2.2 on 2019-06-04 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_app', '0020_auto_20190510_0402'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='close_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='close_price',
            field=models.FloatField(default=0),
        ),
    ]
