# Generated by Django 2.2 on 2019-06-08 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_app', '0021_auto_20190604_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='invalid_reason',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='invalid_reason',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
    ]
